// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/grpc/userpb/userpb.proto

package userpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type User struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Picture              string   `protobuf:"bytes,3,opt,name=picture,proto3" json:"picture,omitempty"`
	Gender               string   `protobuf:"bytes,4,opt,name=gender,proto3" json:"gender,omitempty"`
	Locale               string   `protobuf:"bytes,5,opt,name=locale,proto3" json:"locale,omitempty"`
	Created              string   `protobuf:"bytes,6,opt,name=created,proto3" json:"created,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_291d61dd66b3f9fd, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetPicture() string {
	if m != nil {
		return m.Picture
	}
	return ""
}

func (m *User) GetGender() string {
	if m != nil {
		return m.Gender
	}
	return ""
}

func (m *User) GetLocale() string {
	if m != nil {
		return m.Locale
	}
	return ""
}

func (m *User) GetCreated() string {
	if m != nil {
		return m.Created
	}
	return ""
}

type AuthRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthRequest) Reset()         { *m = AuthRequest{} }
func (m *AuthRequest) String() string { return proto.CompactTextString(m) }
func (*AuthRequest) ProtoMessage()    {}
func (*AuthRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_291d61dd66b3f9fd, []int{1}
}

func (m *AuthRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthRequest.Unmarshal(m, b)
}
func (m *AuthRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthRequest.Marshal(b, m, deterministic)
}
func (m *AuthRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthRequest.Merge(m, src)
}
func (m *AuthRequest) XXX_Size() int {
	return xxx_messageInfo_AuthRequest.Size(m)
}
func (m *AuthRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AuthRequest proto.InternalMessageInfo

func (m *AuthRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type AuthResponse struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Status               int32    `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	Error                string   `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthResponse) Reset()         { *m = AuthResponse{} }
func (m *AuthResponse) String() string { return proto.CompactTextString(m) }
func (*AuthResponse) ProtoMessage()    {}
func (*AuthResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_291d61dd66b3f9fd, []int{2}
}

func (m *AuthResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthResponse.Unmarshal(m, b)
}
func (m *AuthResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthResponse.Marshal(b, m, deterministic)
}
func (m *AuthResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthResponse.Merge(m, src)
}
func (m *AuthResponse) XXX_Size() int {
	return xxx_messageInfo_AuthResponse.Size(m)
}
func (m *AuthResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AuthResponse proto.InternalMessageInfo

func (m *AuthResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *AuthResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *AuthResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func init() {
	proto.RegisterType((*User)(nil), "userpb.User")
	proto.RegisterType((*AuthRequest)(nil), "userpb.AuthRequest")
	proto.RegisterType((*AuthResponse)(nil), "userpb.AuthResponse")
}

func init() { proto.RegisterFile("pkg/grpc/userpb/userpb.proto", fileDescriptor_291d61dd66b3f9fd) }

var fileDescriptor_291d61dd66b3f9fd = []byte{
	// 263 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0x41, 0x4b, 0x03, 0x31,
	0x10, 0x85, 0xad, 0xee, 0x6e, 0x75, 0xda, 0x53, 0x2c, 0x12, 0xc4, 0x43, 0x59, 0x2f, 0x9e, 0x5a,
	0xa8, 0xe0, 0x5d, 0x41, 0xbc, 0xaf, 0x78, 0xf1, 0x20, 0x6c, 0xd3, 0x61, 0x5d, 0xba, 0xdd, 0xc4,
	0x49, 0xe2, 0x2f, 0xf1, 0x07, 0x4b, 0x66, 0x52, 0xd0, 0x53, 0xf2, 0xbd, 0x19, 0x86, 0xf7, 0x1e,
	0xdc, 0xb8, 0x7d, 0xb7, 0xee, 0xc8, 0x99, 0x75, 0xf4, 0x48, 0x6e, 0x9b, 0x9f, 0x95, 0x23, 0x1b,
	0xac, 0xaa, 0x84, 0xea, 0x9f, 0x09, 0x14, 0x6f, 0x1e, 0x49, 0x29, 0x28, 0xc6, 0xf6, 0x80, 0x7a,
	0xb2, 0x9c, 0xdc, 0x5d, 0x34, 0xfc, 0x57, 0x0b, 0x28, 0xf1, 0xd0, 0xf6, 0x83, 0x3e, 0x65, 0x51,
	0x40, 0x69, 0x98, 0xba, 0xde, 0x84, 0x48, 0xa8, 0xcf, 0x58, 0x3f, 0xa2, 0xba, 0x82, 0xaa, 0xc3,
	0x71, 0x87, 0xa4, 0x0b, 0x1e, 0x64, 0x4a, 0xfa, 0x60, 0x4d, 0x3b, 0xa0, 0x2e, 0x45, 0x17, 0x4a,
	0x97, 0x0c, 0x61, 0x1b, 0x70, 0xa7, 0x2b, 0xb9, 0x94, 0xb1, 0xbe, 0x85, 0xd9, 0x63, 0x0c, 0x9f,
	0x0d, 0x7e, 0x45, 0xf4, 0x21, 0x19, 0x09, 0x76, 0x8f, 0x63, 0x76, 0x27, 0x50, 0x7f, 0xc0, 0x5c,
	0x96, 0xbc, 0xb3, 0xa3, 0x47, 0xb5, 0x84, 0x22, 0xa5, 0xe2, 0xa5, 0xd9, 0x66, 0xbe, 0xca, 0x81,
	0x53, 0xbc, 0x86, 0x27, 0xc9, 0x88, 0x0f, 0x6d, 0x88, 0x9e, 0x13, 0x95, 0x4d, 0x26, 0x0e, 0x4a,
	0x64, 0x29, 0x07, 0x12, 0xd8, 0x3c, 0x8b, 0x89, 0x57, 0xa4, 0xef, 0xde, 0xa0, 0x7a, 0x80, 0xe9,
	0x0b, 0x06, 0x2e, 0xeb, 0xf2, 0x78, 0xfb, 0x8f, 0xc9, 0xeb, 0xc5, 0x7f, 0x51, 0x4c, 0xd5, 0x27,
	0x4f, 0xe7, 0xef, 0xb9, 0xec, 0x6d, 0xc5, 0xdd, 0xdf, 0xff, 0x06, 0x00, 0x00, 0xff, 0xff, 0x93,
	0xeb, 0x14, 0xe0, 0x9b, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AuthServiceClient is the client API for AuthService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AuthServiceClient interface {
	GetUser(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*AuthResponse, error)
}

type authServiceClient struct {
	cc *grpc.ClientConn
}

func NewAuthServiceClient(cc *grpc.ClientConn) AuthServiceClient {
	return &authServiceClient{cc}
}

func (c *authServiceClient) GetUser(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*AuthResponse, error) {
	out := new(AuthResponse)
	err := c.cc.Invoke(ctx, "/userpb.AuthService/GetUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthServiceServer is the server API for AuthService service.
type AuthServiceServer interface {
	GetUser(context.Context, *AuthRequest) (*AuthResponse, error)
}

// UnimplementedAuthServiceServer can be embedded to have forward compatible implementations.
type UnimplementedAuthServiceServer struct {
}

func (*UnimplementedAuthServiceServer) GetUser(ctx context.Context, req *AuthRequest) (*AuthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUser not implemented")
}

func RegisterAuthServiceServer(s *grpc.Server, srv AuthServiceServer) {
	s.RegisterService(&_AuthService_serviceDesc, srv)
}

func _AuthService_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/userpb.AuthService/GetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).GetUser(ctx, req.(*AuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AuthService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "userpb.AuthService",
	HandlerType: (*AuthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUser",
			Handler:    _AuthService_GetUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/grpc/userpb/userpb.proto",
}
